import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <TRPCReactProvider>
         <html lang="en" suppressHydrationWarning>
            <body
               className={`${inter.className} antialiased`}
               suppressHydrationWarning
               >
               {children}
            </body>
         </html>
      </TRPCReactProvider>
  );
}
